# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskID', models.CharField(max_length=8)),
                ('TaskName', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=30)),
                ('StartDate', models.DateField()),
                ('DueDate', models.DateField()),
                ('Categories', models.CharField(max_length=100)),
                ('Progress', models.IntegerField()),
                ('Status', models.BooleanField()),
            ],
        ),
    ]
