# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project12780App', '0002_remove_task_taskid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Status',
            field=models.CharField(max_length=20),
        ),
    ]
