# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project12780App', '0004_auto_20171201_0507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CatName', models.CharField(max_length=40)),
                ('Color', models.CharField(max_length=20)),
            ],
        ),
    ]
