# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project12780App', '0005_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
